/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.sun.prism.paint.Paint;
import java.awt.Color;
import java.sql.*;
import java.lang.Object;
/**
 *
 * @author Yugansh Sinha
 */
public class Withdrawl extends javax.swing.JFrame {
    String uID;
    String name,tF;
    String balance,al;
    int a,b;
    /**
     * Creates new form Withdrawl
     */
    public Withdrawl() {
        initComponents();
        getContentPane().setBackground(Color.ORANGE);
        uID=LoginPage.tf;
        name=LoginPage.n;
                System.out.println("name is "+name);
                System.out.println("uid is "+uID);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        tF1 = new javax.swing.JTextField();
        jB1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Enter The Amount To Be Withdrawn");

        jB1.setText("Confirm");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jB1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(tF1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(tF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jB1)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tF1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
    // tF=tF1.getText();  
    }     

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
         
        
        String UniqueId = null;
        String name = null;
        Connection Con;
        String pin;
        int nb=0;
        Statement Stmt;
        Statement Stmt2;
        ResultSet ERs;
        try
        {
            
             /*yaha par uniqueid chahiye aur uske variable ka naam uID rakhna*/ 
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
            Con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE ","system","mayank");
            Stmt=Con.createStatement();
            ERs=Stmt.executeQuery("Select * from ATM");
            Stmt2=Con.createStatement();
            while(ERs.next())
            {
                UniqueId=ERs.getString("UNIQUEID");
                name=ERs.getString("NAME");               //akhri wali entry ki values dalengi loop chal raha hai
                pin=ERs.getString("PIN");
                balance=ERs.getString("BALANCE");
                 // yahan koi dikkat hai
                System.out.println(" ------------------------------------------------------------------");
                System.out.println(balance);
                System.out.println(tF1.getText());
                 b=Integer.parseInt(balance);
                 a=Integer.parseInt(tF1.getText());
                 System.out.println(" ------------------------------------------------------------------");
                 System.out.println("a is "+a);
                 System.out.println("b is "+b);
                 if(UniqueId.equals(uID)){
         
                    System.out.println(name);
                    System.out.println(UniqueId);
                    break;
                    
                }
            }
            if(a<(b-1000))
            {
                nb=(b-a);
                //Integer k=nb;
                String k=Integer.toString(nb);
                System.out.println(k);
                String u="update ATM set BALANCE="+nb+" where UNIQUEID='"+uID+"'";
                int i=Stmt2.executeUpdate(u);
                System.out.println(u);
                System.out.println("balance is "+nb);
            }
            else
            {
                System.out.println("Don't Have Sufficient Balance To Withdraw.");
            }
            new AskReceipt().setVisible(true);
            this.dispose();
        }
        catch(Exception e)
        {System.out.println(e.getMessage());}
    }//GEN-LAST:event_jB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new Withdrawl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tF1;
    // End of variables declaration//GEN-END:variables
}
